# Lists

In [221]:
print('Hello World')        

Hello World


Exercise 1: Given two lists create a third list by picking an odd-index element from the first list and even index elements from the second.

In [222]:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]

list(filter(lambda x: listOne.index(x) % 2 != 0, listOne)) + list(filter(lambda x: listTwo.index(x) % 2 == 0, listTwo))

[6, 12, 18, 4, 12, 20, 28]

 Exercise 2: Given a list, remove the element at index 4 and add it to the 2nd position and at the end of the list

In [223]:
list1 = [34, 54, 67, 89, 11, 43, 94]

element = list1.pop(4)
print(element)
list1.insert(2, element)
list1.append(element)

list1

11


[34, 54, 11, 67, 89, 43, 94, 11]

Exercise 3: Given a list slice it into 3 equal chunks and reverse each chunk

In [224]:
sampleList = [11, 45, 8, 23, 14, 12, 78, 45, 89]
n = k = 3
newList = []

for i in range(len(sampleList)//n):
    if(i == 0):
        newList.extend(sampleList[k-1::-1])
    else:
        newList.extend(sampleList[k-1:k-n-1:-1])
    k = k + n
print(newList)

[8, 45, 11, 12, 14, 23, 89, 45, 78]


Exercise 4: Iterate a given list and count the occurrence of each element and create a dictionary to show the count of each element

In [225]:
list = [11, 45, 8, 11, 23, 45, 23, 45, 89]
dic = {}

for i in set(list):
    dic[i] =list.count(i)

print(dic)

{8: 1, 11: 2, 45: 3, 23: 2, 89: 1}


Exercise 5: Given a two list of equal size create a Python set such that it shows the element from both lists in the pair

In [226]:
l1 =  [2, 3, 4, 5, 6, 7, 8]
l2 = [4, 9, 16, 25, 36, 49, 64]

print(set(zip(l1, l2)))

{(7, 49), (2, 4), (4, 16), (8, 64), (6, 36), (3, 9), (5, 25)}


Exercise 6: Given the following two sets find the intersection and remove those elements from the first set

In [227]:
FirstSet = {65, 42, 78, 83, 23, 57, 29}
SecondSet = {67, 73, 43, 48, 83, 57, 29}

Common = FirstSet & SecondSet
print(FirstSet - Common)

Intersect = FirstSet.intersection(SecondSet)
for i in Intersect:
    FirstSet.remove(i)

print(FirstSet)

{65, 42, 78, 23}
{65, 23, 42, 78}


Exercise 7: Given two sets, Checks if One Set is a subset or superset of another Set. if the subset is found delete all elements from that set

In [228]:
firstSet = {27, 43, 34}
secondSet = {34, 93, 22, 27, 43, 53, 48}

print(f'firstSet is subset of secondSet { firstSet.issubset(secondSet) }')
print(f'secondSet is subset of firstSet { secondSet.issubset(firstSet) }\n')

print(f'firstSet is superset of secondSet { firstSet.issuperset(secondSet) }')
print(f'secondSet is superset of firstSet { secondSet.issuperset(firstSet) }')

if(firstSet.issubset(secondSet)):
    firstSet.clear()

if(secondSet.issubset(firstSet)):
    secondSet.clear()

print(firstSet)
print(secondSet)

firstSet is subset of secondSet True
secondSet is subset of firstSet False

firstSet is superset of secondSet False
secondSet is superset of firstSet True
set()
{48, 34, 53, 22, 27, 43, 93}


Exercise 8: Iterate a given list and Check if a given element already exists in a dictionary as a key’s value if not delete it from the list

In [229]:
rollNumber = [47,64,69,37,76,83,95,97]
sampleDict ={'Jhon':47, 'Emma':69, 'Kelly':76, 'Jason':97}

rollNumber[:] = [i for i in rollNumber if i in sampleDict.values()]

print(rollNumber)


[47, 69, 76, 97]


Exercise 9: Given a dictionary get all values from the dictionary and add them to a list but don’t add duplicates

In [230]:
speed ={'jan':47, 'feb':52, 'march':47, 'April':44, 'May':52, 'June':53, 'july':54, 'Aug':44, 'Sept':54}
newlist = []

for i in set(speed.values()):
    newlist.append(i)

print(newlist)

[44, 47, 52, 53, 54]


Exercise 10: Remove duplicate from a list and create a tuple and find the minimum and maximum number

In [231]:
sampleList = [87, 45, 41, 65, 94, 41, 99, 94]

print(min(tuple(set(sampleList))))
print(max(tuple(set(sampleList))))

41
99


In [232]:
list1=['xyz','zara','PYnative']
print(max(list1))

zara


In [233]:
sampleList = [10, 20, 30, 40, 50]
print(sampleList[-2])
print(sampleList[-4:-1])

40
[20, 30, 40]


In [234]:
l = [None] * 10
print(len(l))
print(l)

10
[None, None, None, None, None, None, None, None, None, None]


In [235]:
aList = [4, 8, 12, 16]
aList[1:4] = [20, 24, 28]
print(aList)

[4, 20, 24, 28]


In [236]:
aList = [5, 10, 15, 25]
print(aList[::-2])

[25, 10]


In [237]:
sampleList = [10, 20, 30, 40]
del sampleList[0:6]
print(sampleList)

[]


# Dictionaries

Exercise 1: Below are the two lists convert it into the dictionary

In [238]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

{i:j for i,j in zip(keys, values)}

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

Exercise 2: Merge following two Python dictionaries into one

In [239]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

dict3 = { **dict1, **dict2 }
dict3

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

Exercise 3: Access the value of key ‘history’ from the below dict


In [240]:
sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}

sampleDict['class']['student']['marks']['history']

80

Exercise 4: Initialize dictionary with default values

In [241]:
employees = ['Kelly', 'Emma', 'John']
defaults = {"designation": 'Application Developer', "salary": 8000 }

dict.fromkeys(employees, defaults)

{'Kelly': {'designation': 'Application Developer', 'salary': 8000},
 'Emma': {'designation': 'Application Developer', 'salary': 8000},
 'John': {'designation': 'Application Developer', 'salary': 8000}}

Exercise 5: Create a new dictionary by extracting the following keys from a below dictionary

In [242]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

keys = ["name", "salary"]

newDict = {}

for i in keys:
    newDict[i] = sampleDict[i]

newDict


{'name': 'Kelly', 'salary': 8000}

Exercise 6: Delete set of keys from a dictionary

In [243]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}

keysToRemove = ["name", "salary"]

print({i: sampleDict[i] for i in sampleDict.keys() if i not in keysToRemove })

print({i: sampleDict[i] for i in sampleDict.keys() - keysToRemove })

{'age': 25, 'city': 'New york'}
{'age': 25, 'city': 'New york'}


Exercise 7: Check if a value 200 exists in a dictionary


In [244]:
sampleDict = {'a': 100, 'b': 200, 'c': 300}

print(200 in sampleDict.values())

True


Exercise 8: Rename key city to location in the following dictionary

In [245]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}

sampleDict['location'] = sampleDict.pop('city')

sampleDict

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}

Exercise 9: Get the key of a minimum value from the following dictionary

In [246]:
sampleDict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}

min(sampleDict, key=sampleDict.get)

'Math'

Exercise 10: Change Brad’s salary to 8500 from a given Python dictionary

In [247]:
sampleDict = {
     'emp1': {'name': 'Jhon', 'salary': 7500},
     'emp2': {'name': 'Emma', 'salary': 8000},
     'emp3': {'name': 'Brad', 'salary': 6500}
}

sampleDict['emp3']['salary'] = 8500

sampleDict

{'emp1': {'name': 'Jhon', 'salary': 7500},
 'emp2': {'name': 'Emma', 'salary': 8000},
 'emp3': {'name': 'Brad', 'salary': 8500}}

In [248]:
student = {
  "name": "Emma",
  "class": 9,
  "marks": 75
}

student['marks']

75

In [249]:
sampleDict = dict([
('first', 1),
('second', 2),
('third', 3)
])

print(sampleDict)

{'first': 1, 'second': 2, 'third': 3}


In [250]:
student = {1: {'name': 'Emma', 'age': '27', 'sex': 'Female'},
           2: {'name': 'Mike', 'age': '22', 'sex': 'Male'}}

student[1]['age']

'27'

In [251]:
dict1 = {"name": "Mike", "salary": 8000}
temp = dict1.pop("age")
print(temp)

KeyError: 'age'

In [252]:
dict1 = {"key1":1, "key2":2}
dict2 = {"key2":2, "key1":1}
print(dict1 == dict2)

True


In [ ]:
sampledict = {}
sampledict

In [ ]:
dict1 = {"name": "Mike", "salary": 8000}
temp = dict1.get("age")
print(temp)

# Tuples

Exercise 1: Reverse the following tuple

In [ ]:
aTuple = (10, 20, 30, 40, 50)

aTuple[::-1]

Exercise 2: Access value 20 from the following tuple


In [ ]:
aTuple = ("Orange", [10, 20, 30], (5, 15, 25))

aTuple[1][1]

Exercise 3: Create a tuple with single item 50

In [ ]:
aTuple = (50,)

aTuple

Exercise 4: Unpack the following tuple into 4 variables


In [ ]:
aTuple = (10, 20, 30, 40)

a,b,c,d = aTuple

print(a,b,c,d)

Exercise 5: Swap the following two tuples

In [ ]:
tuple1 = (11, 22)
tuple2 = (99, 88)

tuple1, tuple2 = tuple2, tuple1

print(tuple1, tuple2)

Exercise 6: Copy element 44 and 55 from the following tuple into a new tuple

In [ ]:
tuple1 = (11, 22, 33, 44, 55, 66)

tuple2 = tuple1[3:-1]
print(tuple2)

Exercise 7: Modify the first item (22) of a list inside a following tuple to 222


In [ ]:
tuple1 = (11, [22, 33], 44, 55)

tuple1[1][0] = 222
print(tuple1)

Exercise 8: Sort a tuple of tuples by 2nd item


In [ ]:
tuple1 = (('a', 23),('b', 37),('c', 11), ('d',29))

tuple1 = tuple(sorted(tuple1, key=lambda x: x[1]))

print(tuple1)

Exercise 9: Counts the number of occurrences of item 50 from a tuple

In [ ]:
tuple1 = (50, 10, 60, 70, 50)

tuple1.count(50)

Exercise 10: Check if all items in the following tuple are the same

In [ ]:
tuple1 = (45, 45, 45, 45)

all(i == tuple1[0] for i in tuple1)

In [ ]:
tuple1 = (10, 20, 30, 40, 50, 60, 70, 80)
#index out of range
position= tuple1.index(10)
print(postion)

In [ ]:
import itertools

tuple1 = (1, 2, 3, 4, 5)
tuple2 = (3, 4, 5, 6, 7)

tuple3 = tuple(item for item in itertools.chain(tuple1, tuple2))
print(tuple3)

In [ ]:
tuple1 = (1120, 'a')
print(max(tuple1))

In [ ]:
aTuple = (100,)
print(aTuple * 2)

In [ ]:
aTuple = "Yellow", 20, "Red"
a, b, c = aTuple
print(a)

In [ ]:
aTuple = (100, 200, 300, 400, 500)
aTuple.pop(2)
print(aTuple)

In [ ]:
aTuple = (100, 200, 300, 400, 500)
print(aTuple[-2])
print(aTuple[-4:-1])

In [ ]:
aTuple = (100, 200, 300, 400, 500)
aTuple[1] = 800
print(aTuple)

# Nd Arrays

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

n = 5
z = np.zeros([n,n],dtype=int)

for i,_ in enumerate(z):
    if i == 0:
        z[i] = 1
    elif i == n-1:
        z[i] = 1
    else:
        z[i][n-i-1] = 1

for i in z:
    for j in i:
        print(j, end=' ')
    print()
    

In [ ]:
import numpy as np
n = 5
z = np.zeros([n,n])
z[:,0] = z[0] = z[-1] = z[:,-1] = 1
z


In [ ]:
n = 5
y = np.zeros([n,n]).flatten()
for i,v in enumerate(y):
    if i%2 != 0:
        y[i] = 1
print(y.reshape([n,n]))

In [ ]:
n = 5
x = np.zeros((n, n))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

In [ ]:
s1 = "Ault"
s2 = "kelly"
s1[:len(s1)//2] + s2 + s1[len(s1)//2:]

In [ ]:
n = 5
x = np.zeros((n, n),dtype=int)
x[(n//2),:] = x[:,(n//2)] = 1
x

In [ ]:
n = 5
for i in range(0,n):
    for j in range(0,i+1):
        print('* ', end='')
    print()

In [ ]:
n = 5
for i in range(1,n+1):
   print('* ' * i)

In [289]:
n = 5
for i in range(0,n):
    for k in range(0,n-i-1):
        print(' ', end=' ')
    for j in range(0,i+1):
        print('* ', end='')
    print()

        * 
      * * 
    * * * 
  * * * * 
* * * * * 


In [301]:
n = 5
for i in range(0,n):
    for k in range(0,n-i-1):
        print(' ', end='')
    for j in range(0,i+1):
        print('* ', end='')
    print()

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [ ]:
n = 5
for i in range(0,n):
    num = 1
    for j in range(0,i+1):
        print(f'{num} ', end='')
        num = num + 1
    print()

In [ ]:
n = 5
num = 1
for i in range(0,n):
    for j in range(0,i+1):
        print(f'{num} ', end='')
        num = num + 1
    print()

In [ ]:
n = 5
for i in range(0,n):
    num = 65
    for j in range(0,i+1):
        print(f'{chr(num)} ', end='')
        num = num + 1
    print()

In [ ]:
n = 5
num = 65
for i in range(0,n):
    for j in range(0,i+1):
        print(f'{chr(num)} ', end='')
        num = num + 1
    print()

In [ ]:
n = 5
num = 65
for i in range(0,n):
    for j in range(0,i+1):
        print(f'{chr(num)} ', end='')
    num = num + 1
    print()

In [ ]:
rows = 6
for i in range(1,rows):
    for j in range(i):
        print(i, end=" ") # print number
    print(" ")

In [ ]:
rows = 6
num = 0
for i in range(rows,0,-1):
    num = num + 1
    for j in range(1,i+1):
        print(num, end=" ") # print number
    print(" ")

In [ ]:
rows = 5
for i in range(rows,0,-1):
    for j in range(1,i+1):
        print(i, end=" ") # print number
    print(" ")

In [ ]:
rows = 5
num = 5
for i in range(rows,0,-1):
    for j in range(1,i+1):
        print(num, end=" ") # print number
    print(" ")

In [266]:
n = 5
for i in range(1,n+1):
    for j in range(i):
        print(j+1, end=" ")
    print(" ")

1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


In [271]:
n = 5
for i in range(1,n+1):
    for j in range(i,0,-1):
        print(j, end=" ")
    print(" ")

1  
2 1  
3 2 1  
4 3 2 1  
5 4 3 2 1  


In [317]:
n = 6
for i in range(1,n):
    for l in range(n-i-1):
        print('  ',end="")
    for j in range(i):
        print(j+1,end=" ")
    for k in range(i-1,0,-1):
        print(k, end=" ")
    print("")

        1 
      1 2 1 
    1 2 3 2 1 
  1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 


In [329]:
n = 12345
r = 0

while(n!=0):
    r = (n%10) + (r*10)
    n=n//10

print(r)

54321


In [4]:
n = 5
for i in range(1, n+1):
    for j in range(n-i):
        print(end=" ")
    for j in range(i-1):
        print('*_', end="")
    print("*")

    *
   *_*
  *_*_*
 *_*_*_*
*_*_*_*_*


In [33]:
l = ['GHI', 'GHIJ', 'GHIJK'] 
l.sort() 
print(l)
min_value = min(len(l[0]), len(l[len(l) - 1])) 
print(min_value)
i = 0 
while (i < min_value and l[0][i] == l[len(l) - 1][i]): 
    i += 1 
    pre = l[0][0: i] 
print(pre)


['GHI', 'GHIJ', 'GHIJK']
3
GHI


In [38]:
a = "bca"
l[:] = [i for i in a]
l.sort()
"".join(l)

'abc'

In [17]:
import numpy as np
n = int(input())
z = np.zeros([n,n],dtype=int)
z[0] = z[-1] = 1
np.fill_diagonal(np.flipud(z),1)
print(z)

[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]


In [18]:
n = int(input())
a = np.zeros([n-2,n-2],dtype=int)
np.pad(a,pad_width=1,constant_values = 1)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])